set names utf8mb4;
set charset utf8mb4;
use huisbieder;

insert into gemeenten(id, postcode, naam)  values (1, '3001','Heverlee');
insert into gemeenten(id, postcode, naam)  values (2, '3010','Kessel-Lo');
insert into gemeenten(id, postcode, naam)  values (3, '3000','Leuven');
insert into gemeenten(id, postcode, naam)  values (4, '3018','Wijgmaal');
insert into gemeenten(id, postcode, naam)  values (5, '3012','Wilsele');
insert into gemeenten(id, postcode, naam)  values (6, '3210','Linden');
insert into gemeenten(id, postcode, naam)  values (7, '3210','Lubbeek');
insert into gemeenten(id, postcode, naam)  values (8, '3212','Pellenberg');
insert into gemeenten(id, postcode, naam)  values (9, '3211','Binkom');
insert into gemeenten(id, postcode, naam)  values (10, '1000','Brussel');
insert into gemeenten(id, postcode, naam)  values (11, '1070','Anderlecht');
insert into gemeenten(id, postcode, naam)  values (12, '1050','Elsene');
insert into gemeenten(id, postcode, naam)  values (13, '1040','Etterbeek');
insert into gemeenten(id, postcode, naam)  values (14, '1140','Evere');
insert into gemeenten(id, postcode, naam)  values (15, '1083','Ganshoren');
insert into gemeenten(id, postcode, naam)  values (16, '1130','Haren');
insert into gemeenten(id, postcode, naam)  values (17, '1090','Jette');
insert into gemeenten(id, postcode, naam)  values (18, '1081','Koekelberg');
insert into gemeenten(id, postcode, naam)  values (19, '1020','Laken');
insert into gemeenten(id, postcode, naam)  values (20, '1120','Neder-Over-Heembeek');
insert into gemeenten(id, postcode, naam)  values (21, '1160','Oudergem');
insert into gemeenten(id, postcode, naam)  values (22, '1030','Schaarbeek');
insert into gemeenten(id, postcode, naam)  values (23, '1082','Sint-Agatha-Berchem');
insert into gemeenten(id, postcode, naam)  values (24, '1060','Sint-Gillis');
insert into gemeenten(id, postcode, naam)  values (25, '1080','Sint-Jans-Molenbeek');
insert into gemeenten(id, postcode, naam)  values (26, '1210','Sint-Joost-ten-Node');
insert into gemeenten(id, postcode, naam)  values (27, '1200','Sint-Lambrechts-Woluwe');
insert into gemeenten(id, postcode, naam)  values (28, '1150','Sint-Pieters-Woluwe');
insert into gemeenten(id, postcode, naam)  values (29, '1180','Ukkel');
insert into gemeenten(id, postcode, naam)  values (30, '1190','Vorst');
insert into gemeenten(id, postcode, naam)  values (31, '1170','Brussel (Watermaal-Bosvoorde)');
insert into gemeenten(id, postcode, naam)  values (32, '1934','Brussel X-Luchthaven Remailing');
insert into gemeenten(id, postcode, naam)  values (33, '1005','Brusselse Hoofdstedelijke Raad');
insert into gemeenten(id, postcode, naam)  values (34, '2100','Deurne');
insert into gemeenten(id, postcode, naam)  values (35, '2180','Ekeren');
insert into gemeenten(id, postcode, naam)  values (36, '2660','Hoboken');
insert into gemeenten(id, postcode, naam)  values (37, '2170','Merksem');
insert into gemeenten(id, postcode, naam)  values (38, '2610','Wilrijk ');
insert into gemeenten(id, postcode, naam)  values (39, '2000','Antwerpen');
insert into gemeenten(id, postcode, naam)  values (40, '2018','Antwerpen');
insert into gemeenten(id, postcode, naam)  values (41, '2020','Antwerpen');
insert into gemeenten(id, postcode, naam)  values (42, '2030','Antwerpen');
insert into gemeenten(id, postcode, naam)  values (43, '2040','Antwerpen');
insert into gemeenten(id, postcode, naam)  values (44, '2050','Antwerpen');
insert into gemeenten(id, postcode, naam)  values (45, '2060','Antwerpen');
insert into gemeenten(id, postcode, naam)  values (46, '2600','Berchem');
insert into gemeenten(id, postcode, naam)  values (47, '2140','Borgerhout');


insert into rollen(id, naam) values
  (1, "klant"),
  (2, "notaris"),
  (3, "admin");
  
insert into gebruikers(id, voornaam, familienaam, straatnaam, huisnummer, gemeenteId, telefoonnummer, email, gebruikersnaam, paswoord) values
-- paswoord: dirkske123
  (1, "Dirk", "Dirkjan", "testStraat", "451", (select id from gemeenten where postcode = '2610'), "016161616", "dirk@test.be", "dirkske", "{bcrypt}$2a$10$QLStSQ.UjNtsX6vV9qc6TOkuCnL8zTNtTdmxummccxP5.KI81yEPi"),
-- paswoord: 123456
  (2, "Jan", "Janssens", "straat", "12", (select id from gemeenten where postcode = '2600'), "016151413", "jan.janssens@test.be", "janneke", "{bcrypt}$2y$10$J67U5e3KQ4YAFuc3POniceOI.vlenGO7gjNxcKE23sxj2nb/GPneW"),
-- paswoord: dominik
  (3, "Domi", "Domi", "straatnaam", "154", (select id from gemeenten where postcode = '2000'), "016151413", "domi@test.be", "dominik", "{bcrypt}$2a$10$RED4gbHCWgVLPP54s6w0AuwvPBrq9jDBCVsZsQUyOuPN8b2wjes3G");
  
insert into gebruikersrollen(gebruikerId, rolId) values
  (1, 1),
  (2, 1),
  (3, 2);
  
insert into panden(id, datumToegevoegd, typeWoning, naam, titel, straatnaam, huisnummer, gemeenteId, bouwjaar, oppervlakte, staatGebouw, aantalgevels, aantalslaapkamers, aantalbadkamers, aantaltoiletten, aantalverdiepingen, living, eetkamer, bureau, kelder, zolder, garage, tuin, terras, veranda, code_epc, dubbelebegelazing, kadastraalinkomen, vrijVanaf, startbod, huidigbod, gebruikerId, startdatum, einddatum, omschrijving) values
-- Regio Leuven
  (1, adddate(timestamp(curdate(), '13:00'), 0), 3, 'Herenhuis', 'Karaktervol herenhuis', 'Kapucijnenvoer', '235', (select id from gemeenten where naam like 'Leuven'), null, 125, 'Gerenoveerd', 2, 3, 1, 3, 3, true, true, true, true, null, true, true, true, null, '20181206-0002112832-2', true, 1088, 'Bij de akte', 580000, 580000, null, adddate(timestamp(curdate(), '13:00'), -1), adddate(timestamp(curdate(), '13:00'), 6), 'Dit op en top smaakvol gerenoveerd herenhuis met behoud van klassieke elementen is zeer gunstig gelegen (mobiscore 9,6/10) binnen de Leuvense ring. Centrum van Leuven bevindt zich op wandelafstand en er is een bushalte vlakbij de woning. In de onmiddellijke nabijheid bevinden zich de oprit van E314 & E40, maar ook IMEC. Kad. geg.: S D, nr 1229A3P0000, opp 1a25 ca. Op het gelijkvloers bevindt zich aan de voorkant een kamer die gebruikt kan worden als opslagruimte, bureau, speelkamer,…. Aan de achterkant vinden we een voll. ingerichte en ruime keuken met eetkamer. De keuken is uitgerust met gloednieuwe toestellen: oven & microgolfoven, Amerikaanse koelkast, vaatwasser, spoelbak, dampkap & kookplaten. Daarnaast bevinden zich ook nog 2 kleine bergruimtes & een toilet met lavabo. Ten slotte is de woning voll. onderkelderd. Als we ons daarna begeven naar de 1ste verd. kunnen we aan de voorkant een kamer vinden die kan dienen als bureau, studeerkamer, bibliotheek,…. Aan de achterkant van het gebouw bevindt zich een zeer ruime living die een mooi uitzicht geeft op de stadstuin. Op de 2de verd. is er een slaapkamer met terras, die zich situeert aan de achterkant v/h gebouw. De badkamer is a/d straatkant gelegen & is uitgerust met ligbad, inloopdouche & 2 lavabo’s, alsook aparte ruimte als dressing. Daarnaast beschikt deze verdieping ook over een toilet. Op de 3de verd. zijn er nog 2 slaapkamers, waarvan 1 met mezzanine. Ook op deze verdieping is er een toiletruimte. De woning heeft een ruimtelijke indeling en werd recent voll. gerenoveerd, waarbij zo veel mogelijk authentieke elementen behouden zijn gebleven. Daarnaast is de woning voll. uitgerust met aluminium ramen (dubb beglazing) en voll. geïsoleerd. Vrij van huur en gebruik – ingenottreding na volledige betaling.'),
  (2, adddate(timestamp(curdate(), '14:00'), 1), 1, 'Handelspand', 'Mooie gelijkvloerse handelsruimte', 'Redingenstraat', '25', (select id from gemeenten where naam like 'Leuven'), 1987, null, null, 2, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, 756, 'Bij de akte', 199000, 225000, 1, adddate(timestamp(curdate(), '12:00'), -10), adddate(timestamp(curdate(), '12:00'), -3), 'Notaris Gwen Daniëls te Oud-Heverlee zal aan de meestbiedende online verkopen via www.biddit.be: Stad LEUVEN. Thans ingericht als kapsalon. Mogelijkheid tot overname van de inboedel. Gekadastreerd wijk D nummer 847/HP0039. K.I. 756 €. Indeling: grote handelsruimte - ruime berging - toilet met spoelbak. VCRO: bestemming: woongebied cultureel, historische en/of esthetische waarde - BPA: gemengde bestemming, Zone voor tuinen - Vergunning - Geen dagvaarding - Voorkooprecht VZW Het samen anders proberen. Watertoets: Overstromingsgevoelig gebied. Inventaris archeologische zones - Historische stadskern van Leuven - UNESCO Werelderfgoed bufferzones - Blanco bodemattest. Verhuurd tot 15/12/2019, huurprijs 783 €. Beschikbaar na betaling van prijs en kosten. . De kandidaat-koper wordt erop gewezen dat hij zelf inlichtingen dient in te winnen over de stedenbouwkundige mogelijkheden en beperkingen van het goed. Inlichtingen ten kantoor Notaris Gwen Daniëls.'),
  (3, adddate(timestamp(curdate(), '15:00'), 1), 0, 'Flat / Studio', 'Uitstekend gelegen ruime studio', 'Tervuursevest', '34-36', (select id from gemeenten where naam like 'Heverlee'), 1989, 375, null, 2, 1, 1, 1, 2, true, null, null, null, null, null, null, null, null, '20190908-0002193333-RES-1', null, 535, 'Bij de akte', 75000, 75000, null, adddate(timestamp(curdate(), '15:00'), 0), adddate(timestamp(curdate(), '15:00'), 14), 'Onder LEUVEN - 4e afdeling In een appartementsgebouw op en met grond, gekadastreerd wijk D, nummer 1177S2P0000: De studio op de tweede verdieping vooraan rechts en gemerkt II-12, thans bekend ten kadaster onder nummer 1177S2P0012, omvattend: a) in private en uitsluitende eigendom: een leefruimte met kookhoek, een slaapruimte, een badkamer met w.c. en sanitaire inrichting, parlofoon; b) in mede-eigendom en gedwongen onverdeeldheid: eenenvijftig duizendsten (51/1.000sten) in de gemene delen, waaronder de grond. INLICHTINGEN: Alle nutsvoorzieningen aanwezig, centrale verwarming op elektriciteit. KI: € 535. Onmiddellijk beschikbaar na betaling van prijs en kosten. Stedenbouw: woongebied, Opslagruimten, Zone voor wonen en handel (BPA Groot-Begijnhof), omgevingsverg. voor slopen woning, bouwen flatgebouw dd. 07/10/1988, geen dagvaarding, geen voorkooprecht, niet overstromingsgevoelig, geen risicozone voor overstromingen, blanco bodemattest. EPC dd. 08/09/2019 (20190908-0002193333-RES-1) met berekend energieverbruik 175kWh/m²). Informatievergadering op dinsdag 12/11/2019 om 18u (inschrijven via lara@kuijpers.be)'),
  (4, adddate(timestamp(curdate(), '16:00'), 2), 3, 'Huis', 'Woning met tuin', 'Albert Woutersstraat', '73', (select id from gemeenten where naam like 'Wilsele'), 1937, 510, null, 2, 2, 1, 2, null, true, null, null, true, true, null, null, true, null, null, null, null, null, 170000, 170000, null, adddate(timestamp(curdate(), '11:00'), 0), adddate(timestamp(curdate(), '11:00'), 5), 'Een rijwoning met tuin gelegen in onmiddellijke nabijheid van centrum Leuven. Beschrijving van de woning: Kelderverdieping: 2 kelderruimtes (deels onderkelderd); Gelijkvloers: inkomhal met trap, leefruimte, keuken, berging en toilet; Tussenverdieping met WC en badkamer; Eerste verdieping: twee ruime slaapkamers, volwaardige trap naar zolder; Zolderverdieping: zolder en zolderkamer; Buiten: terras met tuin. Beschikbaar na betaling prijs en kosten. Kadastrale informatie: sectie D, nummer 216 E 3 P0000, groot 5 a 10 ca. Stedenbouwkundige informatie: bestemming volgens gewestplan: woongebieden - stedenbouwkundige vergunning: gebouw dateert van vóór 1962 - vergunning d.d. 11/8/1986 voor bijbouwen badkamer.'),
  (5, adddate(timestamp(curdate(), '17:00'), 2), 3, 'Huis', 'Huis met grote tuin en vergezicht over leuven', 'Predikherenberg', '13', (select id from gemeenten where naam like 'Kessel-Lo'), 1958, 4045, "Te renoveren", 4, 3, 1, 1, null, true, null, true, true, true, null, true, null, true, '20190211-0002131356-RES-1', null, 1779, 'Bij de akte', 450000, 450000, null, adddate(timestamp(curdate(), '12:00'), 0), adddate(timestamp(curdate(), '12:00'), 8), 'Notaris Lauranne ROOMAN, te Leuven, zal met goedkeuring van de Vrederechter van het Tweede Kanton , te LEUVEN, aan de meestbiedende openbaar verkopen: 3010 Kessel-Lo (Leuven) Een te renoveren woning met grote tuin, gekadastreerd sectie E, nummer 199A2 P0000, groot 40a 45ca en omvattende: Ondergronds: kelder, garage met elektrische poort; Gelijkvloers: inkomhal, vestiaire met WC, woonkamer met veranda, keuken, wasplaats, bureau; Eerste verdieping: drie slaapkamers, badkamer en nachthal, zolder bereikbaar langs luik. KI € 1.779. RUIMTELIJKE ORDENING : Woongebied, Vg, Gmo, Gvkr, Gvv, Niet overstromingsgevoelig. EPC: 633kWh/(m²jaar). Nutsvoorzieningen : elektriciteit, water, CV stookolie. Niet verhuurd - Vrij van gebruik. Vrij en onbelast - gewone voorwaarden. INFOSESSIE: 12 november 2019 om 17.00 uur op het kantoor van notaris ROOMAN PV van toewijzing: 28 november 2019 om 17.00 uur'),
  (6, adddate(timestamp(curdate(), '16:00'), 3), 0, 'Studio', 'Studio', 'Schapenstraat', '17 0102', (select id from gemeenten where naam like 'Leuven'), null, null, null, 2, 1, 1, 1, 1, true, null, null, true, null, null, true, null, null, '20181229-0002114470-1', null, null, 'Bij de akte', 75000, 75000, null, adddate(timestamp(curdate(), '12:00'), -10), adddate(timestamp(curdate(), '12:00'), -3), 'Onder LEUVEN – 4de afdeling In een appartementsgebouw op en met grond, gelegen Schapenstraat 17, gekadastreerd wijk D, nummer 656NP0000: KAVEL 1: De studio “0102”, gelegen op de eerste verdieping aan de voorkant rechts, waaraan verbonden de kelder nummer 1, omvattend: a) in private en uitsluitende eigendom: inkom, leefruimte met kookhoek en badkamer met w.c.; b) in mede-eigendom en gedwongen onverdeeldheid: vijftig duizendsten (50/1.000sten) in de gemene delen, waaronder de grond; Met gereserveerd perceelidentificatienummer 656PP0005. Alle nutsvoorzieningen aanwezig, centrale verwarming op gas. Onmiddellijk beschikbaar na betaling van prijs en kosten. KAVEL 1 thans verhuurd voor € 350 / maand. Stedenbouw: woongebied, Opslagruimten, Zone voor wonen en handel (BPA Groot-Begijnhof), omgevingsverg. voor slopen woning, bouwen flatgebouw dd. 07/10/1988, geen dagvaarding, geen voorkooprecht, niet overstromingsgevoelig, geen risicozone voor overstromingen, blanco bodemattest. KAVEL 1: EPC dd. 29/12/2018 (20181229-0002114470-1) met berekend energieverbruik 287 kWh/m²). Informatievergadering op dinsdag 12 november 2019 om 18u (inschrijven via lara@kuijpers.be)'),
  (7, adddate(timestamp(curdate(), '14:00'), 3), 3, 'Huis', 'Projecteigendom in het centrum van leuven', 'Eugène Gilbertstraat', '9', (select id from gemeenten where naam like 'Leuven'), null, null, null, null, 4, null, null, null, null, null, null, null, null, null, null, null, null, '201906040002166460-RES-1', null, 1834, 'Bij de akte', 400000, 400000, null, adddate(timestamp(curdate(), '12:00'), -1), adddate(timestamp(curdate(), '12:00'), 7), 'Deze woning is rustig gelegen langsheen een zijstraat van de Naamsestraat en vlot bereikbaar met de wagen en het openbaar vervoer. Indeling: - Kelder: 3 kelders (h: 2,20m); - Gelijkvloers: inkomhal, voorplaats, eetplaats, 2e voorplaats, 3e voorplaats, leefruimte, open keuken (niet uitgerust), badkamer (ligbad, lavabo, WC en bide), berging, stookruimte en garage; - 1ste verdieping: nachthal, 4 slaapkamers, 2 zolderkamers, WC, berging; - Zolderverdieping: nachthal, 3 zolderkamers (niet verwarmd) en ruime zolder (niet geïsoleerd); - Afzonderlijk: tuin.'),
  (8, adddate(timestamp(curdate(), '13:00'), 3), 3, 'Huis', 'Goed onderhouden op te frissen woning', 'Hulsberg', '23', (select id from gemeenten where naam like 'Kessel-Lo'), 1972, null, "Op te frissen", 3, 3, null, null, null, true, true, null, true, true, null, true, null, null, null, null, 912, 'Bij de akte', 150000, 150000, null, adddate(timestamp(curdate(), '12:00'), 5), adddate(timestamp(curdate(), '12:00'), 15), 'Goed onderhouden op te frissen woning met inpandige garage (sectionaal poort). Volledig onderkelderd. Recente CV-ketel op gas. PVC ramen. Op eerste verdieping 3 slaapkamers (2 grote + 1 kleine) en badkamer. Zolder. Gelegen in rustige straat maar vlakbij Begijnenbos en op- en afrittencomplex snelweg. Kleuter- en lagere school op minder dan 500m. Grootwarenhuizen op 1 km. Busverbinding vlakbij. Goede fietsverbinding naar Leuven.'),
-- Regio Brussel
  (9, adddate(timestamp(curdate(), '13:00'), 0), 1, 'Commercieel', 'Handels- en opbrengsthuis', 'Gosseliesstraat', '31', (select id from gemeenten where naam like 'Sint-Jans-Molenbeek'), null, null, null, null, 6, null, null, null, true, true, null, true, true, null, true, null, null, null, null, 1739, null, 150000, 150000, null, adddate(timestamp(curdate(), '12:00'), 2), adddate(timestamp(curdate(), '12:00'), 9), 'Gosseliesstraat 31, omv. glvl + 3 verd., 2 woonéénheden, 6 slaapkamers. Opp. 76ca. N.g.k.i. 1.739€. Verhuurd 33%. Best. sted. handel en 2 woonéénheden. EPC (1e v.) E/241, (2e v.) E+/218, (3e v.) G/1.431. Bez. woensdagen 30/10, 6-13/11 van 12u30-14u30 en zaterdagen 2-9-16/11 van 11u30-13u30. Informatie sessie : dins. 12/11/19 van 17-19u ter studie Start biedingen : maandag 11/11/19 om 14u00 Einde biedingen : dinsdag 19/11/19 om 14u00 Ondertekening PV toewijzing : dinsdag 26/11/19 om 9u30 Instelprijs : 180.000€ Bodverhoging : 1.000€ Website : www.biddit.be ref. pand 162913'),
  (10, adddate(timestamp(curdate(), '13:00'), 0), 0, 'Appartement', 'Appartement op 4de verdieping', 'Scheutboschlaan', '4', (select id from gemeenten where naam like 'Sint-Jans-Molenbeek'), 1975, 77, null, null, 2, 1, 1, null, true, null, null, true, null, null, null, null, null, null, null, null, null, 80000, 100000, null, adddate(timestamp(curdate(), '12:00'), -15), adddate(timestamp(curdate(), '12:00'), -5), 'Scheutboschlaan 4. Aangenaam appartement met zonnig terras en twee slaapkamers, ideaal gelegen in een rustige buurt en dicht bij alle voorzieningen. Omv. : woonkamer met terras, keuken, hal, kast, wc, badkamer, 2 slaapkamers, terras - Kelder nr 25 in o.v. Opp. volgens EPC 77m². N.g.k.i. 1.308€. Woongebied. EPC D/179kWh/m²/jaar - CO² 46kg/m²/jaar - cert. nr 20190830-0000555414-01-8 geldig tot 30/8/29. Elektr. inst. niet conf. Bez. woensdag 30/10, 6-13/11 van 14-16u en zaterdag 2-9-16/11 van 10-12u. Start biedingen : dinsdag 12/11/19 om 13u00 Einde biedingen : woensdag 20/11/19 om 13u00 Ondertekening PV toewijzing : maandag 25/11/19 om 16u00 Instelprijs : 80.000€ Bodverhoging : 1.000€ Website : www.biddit.be ref. pand 159450'),
  (11, adddate(timestamp(curdate(), '13:00'), 1), 3, 'Bel-etagewoning', 'Goed gelegen bel-étage woning in het centrum van evere', 'Godfroid Kurthstraat', '43', (select id from gemeenten where naam like 'Evere'), null, null, null, 2, 3, 1, 2, null, true, false, null, true, null, null, null, null, null, true, null, null, 'Bij de akte', 230000, 230000, null, adddate(timestamp(curdate(), '12:00'), -3), adddate(timestamp(curdate(), '12:00'), 10), 'Gemeente EVERE - 2e afd.: bel-étagewoning, gevelbreedte : 6,16m. GLV: hall, wc, 1 garage, kamer (12 m² ), keuken met douche (17 m² ), overdekte ruimte (17 m² ). 1ste verd.: living met open haard (50 m² ), keuken (7 m² ), terras (4,8 m²). 2de verd.: 2 kamers (14 en 18 m² ), badkamer met wc en ligbad. Volledig onderkelderd. Verwarming gas, EPC G/80, EK niet conform. Niet-geïndexeerd kadastraal inkomen: € 1.340. Vrij na betaling prijs en kosten. Ligging : Godfroid Kurthstraat 43 - Evere (Leopold III wijk - Hendrik Consciencelaan). Centraal gelegen op wandelafstand van scholen, handelszaken, openbaar vervoer (bus, trein, vélo), nabij gelegen parken en sportcentrum (tennis, hockey, zwembad), op 5 minuten van E40 en ring van Brussel. Stedenbouw: gemengd gebied, geen RPA, BBP of VV, geen RVV, sted. vergunningen: 27/7/1938, 9/12/1970 en 03/08/2018, geen gekende bouwmisdrijven. MAISON BEL-ÉTAGE Idéalement située quartier Léopold III - Avenue Henri Conscience. Cadastré : Commune de Evere, 2ème div., sect D, nr. 0247/P9P0000, d’une contenance de 70ca, RC non indexé : € 1.340. Maison bel-étage ayant 6,16m de façade - RDC : hall, wc, 1 garage, chambre (12 m² ), cuisine avec douche (17m²), espace recouvert (17m²) - 1er ETG. : living avec feu ouvert (50m²), cuisine (7m²), terrasse (4,8m²) - 2ème ETG. : 2 chambres (14 et 18m²), salle de bains avec wc et baignoire. Caves sous toute la surface de la maison. Chauffage au gaz, PEB G/80, CE non conforme. Libre après paiement prix et frais. Situation centrale à distance de marche d’écoles, commerces, hypermarchés, transports communs (bus STIB, DE LIJN, train, vélo), à proximité de parcs et du complexe sportif (tennis, hockey, piscine), à 5 minutes de l’E40 et du ring de Bruxelles. Urbanisme : zone mixte, permis d’urbanisme : 27/7/1938, 9/12/1970 et 03/08/2018, pas d’infraction de construction connue. Pas dans un périmètre de PAD, PPAS, lotissement ou de préemption');


